name: Publish LaTeX Resumes

on:
  push:
    paths:
      - 'resume/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Compile resume.tex
      - name: Compile resume.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          working_directory: resume

      # Compile short_resume.tex
      - name: Compile short_resume.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: short_resume.tex
          working_directory: resume
          
      # Move compiled PDFs to assets directory
      - name: Move compiled PDFs to assets directory
        run: |
          cp resume/*.pdf assets/pdfs/resume/

      # Commit and push the generated PDF files
      - name: Commit PDFs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/pdfs/resume/*.pdf
          git commit -m "Compile LaTeX files to PDF" -a || echo "No changes to commit"
          git push
